# Generated by Django 4.2.30 on 2026-07-19 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resultapp', '0008_attendance_subject_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_classes', models.ManyToManyField(blank=True, help_text='Classes this teacher is allowed to view/manage', related_name='teachers', to='resultapp.class')),
                ('assigned_subjects', models.ManyToManyField(blank=True, help_text='Subjects this teacher is responsible for', related_name='teachers', to='resultapp.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
