# Generated by Django 4.2.30 on 2026-08-18 09:45

from django.db import migrations, models
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

def convert_dob_to_date(apps, schema_editor):
    Student = apps.get_model('resultapp', 'Student')
    for student in Student.objects.all():
        dob_str = student.dob
        if not dob_str:
            student.dob = None
            student.save()
            continue
        
        parsed_date = None
        # Try formats: YYYY-MM-DD, DD-MM-YYYY, DD/MM/YYYY
        for fmt in ('%Y-%m-%d', '%d-%m-%Y', '%d/%m/%Y'):
            try:
                parsed_date = datetime.strptime(dob_str.strip(), fmt).date()
                break
            except ValueError:
                continue
                
        if parsed_date:
            student.dob = parsed_date.strftime('%Y-%m-%d')
        else:
            # Cannot convert. Log a warning and set to None.
            print(f"WARNING: Student ID {student.id} ({student.name}) has unparseable DOB: '{dob_str}'. Setting to None.")
            logger.warning("Student ID %s (%s) has unparseable DOB: '%s'. Setting to None.", student.id, student.name, dob_str)
            student.dob = None
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0012_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.RunPython(convert_dob_to_date, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]

