# Generated by Django 4.2.30 on 2026-08-20 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resultapp', '0013_holiday_parent_email_alerts_student_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(max_length=30)),
                ('message_type', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('response_payload', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='semester',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('target_model', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
